- name: function testiing
  hosts: local
  connection: local
  vars:
    fullname: "Pulikanti Nageswarreddy"
    devtools: java, python, c, c++
    ipv4_invalid: 192.168.0.1k
    ipv4: 192.168.0.1

  tasks:
    - name: default vars
      ansible.builtin.debug:
        msg: "{{fullname | default('Nageswarreddy')}}"
    - name: convert string to lists
      ansible.builtin.debug:
        msg: "{{ devtools | split(',') }}"
    - name: convert to lower
      ansible.builtin.debug:
        msg: "{{ fullname | lower }}"
    - name: convert to upper
      ansible.builtin.debug:
        msg: "{{ fullname | upper }}"
    - name: check ipv4
      ansible.builtin.debug:
        msg: "{{ ipv4 | ansible.utils.ipv4 }}"
    - name: check ipv4
      ansible.builtin.debug:
        msg: "{{ ipv4_invalid | ansible.utils.ipv4 }}"

    - name: grep for root
      ansible.builtin.shell: cat /etc/passwd | grep -i root
      register: out
    - name: print the root data
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: redirect output through command
      ansible.builtin.command: ls -ltr > /tmp/out.txt
      register: data
      ignore_errors: true

    - name: print the routed data
      ansible.builtin.debug:
        msg: "{{ data }}"

    - name: redirect output through shell
      ansible.builtin.shell: ls -ltr > /tmp/out.txt
      register: data2

    - name: print the routed data
      ansible.builtin.debug:
        msg: "{{ data2 }}"
  # become: yes
