- name: function testiing
  hosts: local
  connection: local
  vars:
    fullname: "Pulikanti Nageswarreddy"

  tasks:
    - name: default vars
      ansible.builtin.debug:
        msg: "{{fullname | default('Nageswarreddy')}}"
