- name: function testiing
  hosts: local
  connection: local
  vars:
    fullname: "Pulikanti Nageswarreddy"
    devtools: java, python, c, c++
    ipv4: 192.168.0.1k

  tasks:
    - name: default vars
      ansible.builtin.debug:
        msg: "{{fullname | default('Nageswarreddy')}}"
    - name: convert string to lists
      ansible.builtin.debug:
        msg: "{{ devtools | split(',') }}"
    - name: convert to lower
      ansible.builtin.debug:
        msg: "{{ fullname | lower }}"
    - name: convert to upper
      ansible.builtin.debug:
        msg: "{{ fullname | upper }}"
    - name: check ipv4
      ansible.builtin.debug:
        msg: "{{ ipv4 | ansible.utils.ipv4 }}"
